<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Resource;

class PluginResource extends \Jane\OpenApiRuntime\Client\Psr7HttplugResource
{
    use PluginResourceTrait;
}
