<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Resource;

use Jane\OpenApiRuntime\Client\QueryParam;

trait SessionExperimentalAsyncResourceTrait
{
    /**
     * Start a new interactive session with a server. Session allows server to call back to the client for advanced capabilities.

    > **Note**: This endpoint is *experimental* and only available if the daemon is started with experimental
    > features enabled. The specifications for this endpoint may still change in a future version of the API.

    ### Hijacking

    This endpoint hijacks the HTTP connection to HTTP2 transport that allows the client to expose gPRC services on that connection.

    For example, the client sends this request to upgrade the connection:

    ```
    POST /session HTTP/1.1
    Upgrade: h2c
    Connection: Upgrade
    ```

    The Docker daemon will respond with a `101 UPGRADED` response follow with the raw stream:

    ```
    HTTP/1.1 101 UPGRADED
    Connection: Upgrade
    Upgrade: h2c
    ```

     *
     * @param array                  $parameters        List of parameters
     * @param string                 $fetch             Fetch mode (object or response)
     * @param \Amp\CancellationToken $cancellationToken Token to cancel the request
     *
     * @throws \Docker\API\Exception\SessionBadRequestException
     * @throws \Docker\API\Exception\SessionInternalServerErrorException
     *
     * @return \Amp\Promise<\Amp\Artax\Response|null>
     */
    public function session(array $parameters = [], string $fetch = self::FETCH_OBJECT, \Amp\CancellationToken $cancellationToken = null): \Amp\Promise
    {
        return \Amp\call(function () use ($parameters, $fetch, $cancellationToken) {
            $queryParam = new QueryParam();
            $url = '/session';
            $url = $url . ('?' . $queryParam->buildQueryString($parameters));
            $headers = array_merge(['Accept' => ['application/json']], $queryParam->buildHeaders($parameters));
            $body = $queryParam->buildFormDataString($parameters);
            $request = new \Amp\Artax\Request($url, 'POST');
            $request = $request->withHeaders($headers);
            $request = $request->withBody($body);
            $response = (yield $this->httpClient->request($request, [], $cancellationToken));
            if (self::FETCH_OBJECT === $fetch) {
                if (101 === $response->getStatus()) {
                    return null;
                }
                if (400 === $response->getStatus()) {
                    throw new \Docker\API\Exception\SessionBadRequestException($this->serializer->deserialize((yield $response->getBody()), 'Docker\\API\\Model\\ErrorResponse', 'json'));
                }
                if (500 === $response->getStatus()) {
                    throw new \Docker\API\Exception\SessionInternalServerErrorException($this->serializer->deserialize((yield $response->getBody()), 'Docker\\API\\Model\\ErrorResponse', 'json'));
                }
            }

            return $response;
        });
    }
}
