<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Normalizer;

use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class DistributionNameJsonGetResponse200PlatformsItemNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Docker\\API\\Model\\DistributionNameJsonGetResponse200PlatformsItem';
    }

    public function supportsNormalization($data, $format = null)
    {
        return $data instanceof \Docker\API\Model\DistributionNameJsonGetResponse200PlatformsItem;
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            return null;
        }
        $object = new \Docker\API\Model\DistributionNameJsonGetResponse200PlatformsItem();
        if (property_exists($data, 'Architecture') && $data->{'Architecture'} !== null) {
            $object->setArchitecture($data->{'Architecture'});
        }
        if (property_exists($data, 'OS') && $data->{'OS'} !== null) {
            $object->setOS($data->{'OS'});
        }
        if (property_exists($data, 'OSVersion') && $data->{'OSVersion'} !== null) {
            $object->setOSVersion($data->{'OSVersion'});
        }
        if (property_exists($data, 'OSFeatures') && $data->{'OSFeatures'} !== null) {
            $values = [];
            foreach ($data->{'OSFeatures'} as $value) {
                $values[] = $value;
            }
            $object->setOSFeatures($values);
        }
        if (property_exists($data, 'Variant') && $data->{'Variant'} !== null) {
            $object->setVariant($data->{'Variant'});
        }
        if (property_exists($data, 'Features') && $data->{'Features'} !== null) {
            $values_1 = [];
            foreach ($data->{'Features'} as $value_1) {
                $values_1[] = $value_1;
            }
            $object->setFeatures($values_1);
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        if (null !== $object->getArchitecture()) {
            $data->{'Architecture'} = $object->getArchitecture();
        }
        if (null !== $object->getOS()) {
            $data->{'OS'} = $object->getOS();
        }
        if (null !== $object->getOSVersion()) {
            $data->{'OSVersion'} = $object->getOSVersion();
        }
        if (null !== $object->getOSFeatures()) {
            $values = [];
            foreach ($object->getOSFeatures() as $value) {
                $values[] = $value;
            }
            $data->{'OSFeatures'} = $values;
        }
        if (null !== $object->getVariant()) {
            $data->{'Variant'} = $object->getVariant();
        }
        if (null !== $object->getFeatures()) {
            $values_1 = [];
            foreach ($object->getFeatures() as $value_1) {
                $values_1[] = $value_1;
            }
            $data->{'Features'} = $values_1;
        }

        return $data;
    }
}
