<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class ContainersIdExecPostBody
{
    /**
     * @var bool
     */
    protected $attachStdin;
    /**
     * @var bool
     */
    protected $attachStdout;
    /**
     * @var bool
     */
    protected $attachStderr;
    /**
     * @var string
     */
    protected $detachKeys;
    /**
     * @var bool
     */
    protected $tty;
    /**
     * @var string[]
     */
    protected $env;
    /**
     * @var string[]
     */
    protected $cmd;
    /**
     * @var bool
     */
    protected $privileged;
    /**
     * @var string
     */
    protected $user;

    /**
     * @return bool
     */
    public function getAttachStdin(): ?bool
    {
        return $this->attachStdin;
    }

    /**
     * @param bool $attachStdin
     *
     * @return self
     */
    public function setAttachStdin(?bool $attachStdin): self
    {
        $this->attachStdin = $attachStdin;

        return $this;
    }

    /**
     * @return bool
     */
    public function getAttachStdout(): ?bool
    {
        return $this->attachStdout;
    }

    /**
     * @param bool $attachStdout
     *
     * @return self
     */
    public function setAttachStdout(?bool $attachStdout): self
    {
        $this->attachStdout = $attachStdout;

        return $this;
    }

    /**
     * @return bool
     */
    public function getAttachStderr(): ?bool
    {
        return $this->attachStderr;
    }

    /**
     * @param bool $attachStderr
     *
     * @return self
     */
    public function setAttachStderr(?bool $attachStderr): self
    {
        $this->attachStderr = $attachStderr;

        return $this;
    }

    /**
     * @return string
     */
    public function getDetachKeys(): ?string
    {
        return $this->detachKeys;
    }

    /**
     * @param string $detachKeys
     *
     * @return self
     */
    public function setDetachKeys(?string $detachKeys): self
    {
        $this->detachKeys = $detachKeys;

        return $this;
    }

    /**
     * @return bool
     */
    public function getTty(): ?bool
    {
        return $this->tty;
    }

    /**
     * @param bool $tty
     *
     * @return self
     */
    public function setTty(?bool $tty): self
    {
        $this->tty = $tty;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getEnv(): ?array
    {
        return $this->env;
    }

    /**
     * @param string[] $env
     *
     * @return self
     */
    public function setEnv(?array $env): self
    {
        $this->env = $env;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getCmd(): ?array
    {
        return $this->cmd;
    }

    /**
     * @param string[] $cmd
     *
     * @return self
     */
    public function setCmd(?array $cmd): self
    {
        $this->cmd = $cmd;

        return $this;
    }

    /**
     * @return bool
     */
    public function getPrivileged(): ?bool
    {
        return $this->privileged;
    }

    /**
     * @param bool $privileged
     *
     * @return self
     */
    public function setPrivileged(?bool $privileged): self
    {
        $this->privileged = $privileged;

        return $this;
    }

    /**
     * @return string
     */
    public function getUser(): ?string
    {
        return $this->user;
    }

    /**
     * @param string $user
     *
     * @return self
     */
    public function setUser(?string $user): self
    {
        $this->user = $user;

        return $this;
    }
}
