<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class ContainersIdJsonGetResponse200State
{
    /**
     * @var string
     */
    protected $status;
    /**
     * @var bool
     */
    protected $running;
    /**
     * @var bool
     */
    protected $paused;
    /**
     * @var bool
     */
    protected $restarting;
    /**
     * @var bool
     */
    protected $oOMKilled;
    /**
     * @var bool
     */
    protected $dead;
    /**
     * @var int
     */
    protected $pid;
    /**
     * @var int
     */
    protected $exitCode;
    /**
     * @var string
     */
    protected $error;
    /**
     * @var string
     */
    protected $startedAt;
    /**
     * @var string
     */
    protected $finishedAt;

    /**
     * @return string
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * @param string $status
     *
     * @return self
     */
    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return bool
     */
    public function getRunning(): ?bool
    {
        return $this->running;
    }

    /**
     * @param bool $running
     *
     * @return self
     */
    public function setRunning(?bool $running): self
    {
        $this->running = $running;

        return $this;
    }

    /**
     * @return bool
     */
    public function getPaused(): ?bool
    {
        return $this->paused;
    }

    /**
     * @param bool $paused
     *
     * @return self
     */
    public function setPaused(?bool $paused): self
    {
        $this->paused = $paused;

        return $this;
    }

    /**
     * @return bool
     */
    public function getRestarting(): ?bool
    {
        return $this->restarting;
    }

    /**
     * @param bool $restarting
     *
     * @return self
     */
    public function setRestarting(?bool $restarting): self
    {
        $this->restarting = $restarting;

        return $this;
    }

    /**
     * @return bool
     */
    public function getOOMKilled(): ?bool
    {
        return $this->oOMKilled;
    }

    /**
     * @param bool $oOMKilled
     *
     * @return self
     */
    public function setOOMKilled(?bool $oOMKilled): self
    {
        $this->oOMKilled = $oOMKilled;

        return $this;
    }

    /**
     * @return bool
     */
    public function getDead(): ?bool
    {
        return $this->dead;
    }

    /**
     * @param bool $dead
     *
     * @return self
     */
    public function setDead(?bool $dead): self
    {
        $this->dead = $dead;

        return $this;
    }

    /**
     * @return int
     */
    public function getPid(): ?int
    {
        return $this->pid;
    }

    /**
     * @param int $pid
     *
     * @return self
     */
    public function setPid(?int $pid): self
    {
        $this->pid = $pid;

        return $this;
    }

    /**
     * @return int
     */
    public function getExitCode(): ?int
    {
        return $this->exitCode;
    }

    /**
     * @param int $exitCode
     *
     * @return self
     */
    public function setExitCode(?int $exitCode): self
    {
        $this->exitCode = $exitCode;

        return $this;
    }

    /**
     * @return string
     */
    public function getError(): ?string
    {
        return $this->error;
    }

    /**
     * @param string $error
     *
     * @return self
     */
    public function setError(?string $error): self
    {
        $this->error = $error;

        return $this;
    }

    /**
     * @return string
     */
    public function getStartedAt(): ?string
    {
        return $this->startedAt;
    }

    /**
     * @param string $startedAt
     *
     * @return self
     */
    public function setStartedAt(?string $startedAt): self
    {
        $this->startedAt = $startedAt;

        return $this;
    }

    /**
     * @return string
     */
    public function getFinishedAt(): ?string
    {
        return $this->finishedAt;
    }

    /**
     * @param string $finishedAt
     *
     * @return self
     */
    public function setFinishedAt(?string $finishedAt): self
    {
        $this->finishedAt = $finishedAt;

        return $this;
    }
}
