<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class ContainersCreatePostBodyNetworkingConfig
{
    /**
     * @var EndpointSettings[]
     */
    protected $endpointsConfig;

    /**
     * @return EndpointSettings[]
     */
    public function getEndpointsConfig(): ?\ArrayObject
    {
        return $this->endpointsConfig;
    }

    /**
     * @param EndpointSettings[] $endpointsConfig
     *
     * @return self
     */
    public function setEndpointsConfig(?\ArrayObject $endpointsConfig): self
    {
        $this->endpointsConfig = $endpointsConfig;

        return $this;
    }
}
