<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class Driver
{
    /**
     * Name of the driver.
     *
     * @var string
     */
    protected $name;
    /**
     * Key/value map of driver-specific options.
     *
     * @var string[]
     */
    protected $options;

    /**
     * Name of the driver.
     *
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Name of the driver.
     *
     * @param string $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Key/value map of driver-specific options.
     *
     * @return string[]
     */
    public function getOptions(): ?\ArrayObject
    {
        return $this->options;
    }

    /**
     * Key/value map of driver-specific options.
     *
     * @param string[] $options
     *
     * @return self
     */
    public function setOptions(?\ArrayObject $options): self
    {
        $this->options = $options;

        return $this;
    }
}
