<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class EndpointSettings
{
    /**
     * @var EndpointSettingsIPAMConfig
     */
    protected $iPAMConfig;
    /**
     * @var string[]
     */
    protected $links;
    /**
     * @var string[]
     */
    protected $aliases;
    /**
     * @var string
     */
    protected $networkID;
    /**
     * @var string
     */
    protected $endpointID;
    /**
     * @var string
     */
    protected $gateway;
    /**
     * @var string
     */
    protected $iPAddress;
    /**
     * @var int
     */
    protected $iPPrefixLen;
    /**
     * @var string
     */
    protected $iPv6Gateway;
    /**
     * @var string
     */
    protected $globalIPv6Address;
    /**
     * @var int
     */
    protected $globalIPv6PrefixLen;
    /**
     * @var string
     */
    protected $macAddress;

    /**
     * @return EndpointSettingsIPAMConfig
     */
    public function getIPAMConfig(): ?EndpointSettingsIPAMConfig
    {
        return $this->iPAMConfig;
    }

    /**
     * @param EndpointSettingsIPAMConfig $iPAMConfig
     *
     * @return self
     */
    public function setIPAMConfig(?EndpointSettingsIPAMConfig $iPAMConfig): self
    {
        $this->iPAMConfig = $iPAMConfig;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getLinks(): ?array
    {
        return $this->links;
    }

    /**
     * @param string[] $links
     *
     * @return self
     */
    public function setLinks(?array $links): self
    {
        $this->links = $links;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getAliases(): ?array
    {
        return $this->aliases;
    }

    /**
     * @param string[] $aliases
     *
     * @return self
     */
    public function setAliases(?array $aliases): self
    {
        $this->aliases = $aliases;

        return $this;
    }

    /**
     * @return string
     */
    public function getNetworkID(): ?string
    {
        return $this->networkID;
    }

    /**
     * @param string $networkID
     *
     * @return self
     */
    public function setNetworkID(?string $networkID): self
    {
        $this->networkID = $networkID;

        return $this;
    }

    /**
     * @return string
     */
    public function getEndpointID(): ?string
    {
        return $this->endpointID;
    }

    /**
     * @param string $endpointID
     *
     * @return self
     */
    public function setEndpointID(?string $endpointID): self
    {
        $this->endpointID = $endpointID;

        return $this;
    }

    /**
     * @return string
     */
    public function getGateway(): ?string
    {
        return $this->gateway;
    }

    /**
     * @param string $gateway
     *
     * @return self
     */
    public function setGateway(?string $gateway): self
    {
        $this->gateway = $gateway;

        return $this;
    }

    /**
     * @return string
     */
    public function getIPAddress(): ?string
    {
        return $this->iPAddress;
    }

    /**
     * @param string $iPAddress
     *
     * @return self
     */
    public function setIPAddress(?string $iPAddress): self
    {
        $this->iPAddress = $iPAddress;

        return $this;
    }

    /**
     * @return int
     */
    public function getIPPrefixLen(): ?int
    {
        return $this->iPPrefixLen;
    }

    /**
     * @param int $iPPrefixLen
     *
     * @return self
     */
    public function setIPPrefixLen(?int $iPPrefixLen): self
    {
        $this->iPPrefixLen = $iPPrefixLen;

        return $this;
    }

    /**
     * @return string
     */
    public function getIPv6Gateway(): ?string
    {
        return $this->iPv6Gateway;
    }

    /**
     * @param string $iPv6Gateway
     *
     * @return self
     */
    public function setIPv6Gateway(?string $iPv6Gateway): self
    {
        $this->iPv6Gateway = $iPv6Gateway;

        return $this;
    }

    /**
     * @return string
     */
    public function getGlobalIPv6Address(): ?string
    {
        return $this->globalIPv6Address;
    }

    /**
     * @param string $globalIPv6Address
     *
     * @return self
     */
    public function setGlobalIPv6Address(?string $globalIPv6Address): self
    {
        $this->globalIPv6Address = $globalIPv6Address;

        return $this;
    }

    /**
     * @return int
     */
    public function getGlobalIPv6PrefixLen(): ?int
    {
        return $this->globalIPv6PrefixLen;
    }

    /**
     * @param int $globalIPv6PrefixLen
     *
     * @return self
     */
    public function setGlobalIPv6PrefixLen(?int $globalIPv6PrefixLen): self
    {
        $this->globalIPv6PrefixLen = $globalIPv6PrefixLen;

        return $this;
    }

    /**
     * @return string
     */
    public function getMacAddress(): ?string
    {
        return $this->macAddress;
    }

    /**
     * @param string $macAddress
     *
     * @return self
     */
    public function setMacAddress(?string $macAddress): self
    {
        $this->macAddress = $macAddress;

        return $this;
    }
}
