<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class ExecIdStartPostBody
{
    /**
     * @var bool
     */
    protected $detach;
    /**
     * @var bool
     */
    protected $tty;

    /**
     * @return bool
     */
    public function getDetach(): ?bool
    {
        return $this->detach;
    }

    /**
     * @param bool $detach
     *
     * @return self
     */
    public function setDetach(?bool $detach): self
    {
        $this->detach = $detach;

        return $this;
    }

    /**
     * @return bool
     */
    public function getTty(): ?bool
    {
        return $this->tty;
    }

    /**
     * @param bool $tty
     *
     * @return self
     */
    public function setTty(?bool $tty): self
    {
        $this->tty = $tty;

        return $this;
    }
}
