<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class HostConfig
{
    /**
     * @var int
     */
    protected $cpuShares;
    /**
     * @var int
     */
    protected $memory;
    /**
     * @var string
     */
    protected $cgroupParent;
    /**
     * @var int
     */
    protected $blkioWeight;
    /**
     * @var ResourcesBlkioWeightDeviceItem[]
     */
    protected $blkioWeightDevice;
    /**
     * @var ThrottleDevice[]
     */
    protected $blkioDeviceReadBps;
    /**
     * @var ThrottleDevice[]
     */
    protected $blkioDeviceWriteBps;
    /**
     * @var ThrottleDevice[]
     */
    protected $blkioDeviceReadIOps;
    /**
     * @var ThrottleDevice[]
     */
    protected $blkioDeviceWriteIOps;
    /**
     * @var int
     */
    protected $cpuPeriod;
    /**
     * @var int
     */
    protected $cpuQuota;
    /**
     * @var int
     */
    protected $cpuRealtimePeriod;
    /**
     * @var int
     */
    protected $cpuRealtimeRuntime;
    /**
     * @var string
     */
    protected $cpusetCpus;
    /**
     * @var string
     */
    protected $cpusetMems;
    /**
     * @var DeviceMapping[]
     */
    protected $devices;
    /**
     * @var int
     */
    protected $diskQuota;
    /**
     * @var int
     */
    protected $kernelMemory;
    /**
     * @var int
     */
    protected $memoryReservation;
    /**
     * @var int
     */
    protected $memorySwap;
    /**
     * @var int
     */
    protected $memorySwappiness;
    /**
     * @var int
     */
    protected $nanoCPUs;
    /**
     * @var bool
     */
    protected $oomKillDisable;
    /**
     * @var int
     */
    protected $pidsLimit;
    /**
     * @var ResourcesUlimitsItem[]
     */
    protected $ulimits;
    /**
     * @var int
     */
    protected $cpuCount;
    /**
     * @var int
     */
    protected $cpuPercent;
    /**
     * @var int
     */
    protected $iOMaximumIOps;
    /**
     * @var int
     */
    protected $iOMaximumBandwidth;
    /**
     * @var string[]
     */
    protected $binds;
    /**
     * @var string
     */
    protected $containerIDFile;
    /**
     * @var HostConfigLogConfig
     */
    protected $logConfig;
    /**
     * @var string
     */
    protected $networkMode;
    /**
     * @var HostConfigPortBindingsItem[]
     */
    protected $portBindings;
    /**
     * @var RestartPolicy
     */
    protected $restartPolicy;
    /**
     * @var bool
     */
    protected $autoRemove;
    /**
     * @var string
     */
    protected $volumeDriver;
    /**
     * @var string[]
     */
    protected $volumesFrom;
    /**
     * @var Mount[]
     */
    protected $mounts;
    /**
     * @var string[]
     */
    protected $capAdd;
    /**
     * @var string[]
     */
    protected $capDrop;
    /**
     * @var string[]
     */
    protected $dns;
    /**
     * @var string[]
     */
    protected $dnsOptions;
    /**
     * @var string[]
     */
    protected $dnsSearch;
    /**
     * @var string[]
     */
    protected $extraHosts;
    /**
     * @var string[]
     */
    protected $groupAdd;
    /**
     * @var string
     */
    protected $ipcMode;
    /**
     * @var string
     */
    protected $cgroup;
    /**
     * @var string[]
     */
    protected $links;
    /**
     * @var int
     */
    protected $oomScoreAdj;
    /**
     * @var string
     */
    protected $pidMode;
    /**
     * @var bool
     */
    protected $privileged;
    /**
     * @var bool
     */
    protected $publishAllPorts;
    /**
     * @var bool
     */
    protected $readonlyRootfs;
    /**
     * @var string[]
     */
    protected $securityOpt;
    /**
     * @var string[]
     */
    protected $storageOpt;
    /**
     * @var string[]
     */
    protected $tmpfs;
    /**
     * @var string
     */
    protected $uTSMode;
    /**
     * @var string
     */
    protected $usernsMode;
    /**
     * @var int
     */
    protected $shmSize;
    /**
     * @var string[]
     */
    protected $sysctls;
    /**
     * @var string
     */
    protected $runtime;
    /**
     * @var int[]
     */
    protected $consoleSize;
    /**
     * @var string
     */
    protected $isolation;

    /**
     * @return int
     */
    public function getCpuShares(): ?int
    {
        return $this->cpuShares;
    }

    /**
     * @param int $cpuShares
     *
     * @return self
     */
    public function setCpuShares(?int $cpuShares): self
    {
        $this->cpuShares = $cpuShares;

        return $this;
    }

    /**
     * @return int
     */
    public function getMemory(): ?int
    {
        return $this->memory;
    }

    /**
     * @param int $memory
     *
     * @return self
     */
    public function setMemory(?int $memory): self
    {
        $this->memory = $memory;

        return $this;
    }

    /**
     * @return string
     */
    public function getCgroupParent(): ?string
    {
        return $this->cgroupParent;
    }

    /**
     * @param string $cgroupParent
     *
     * @return self
     */
    public function setCgroupParent(?string $cgroupParent): self
    {
        $this->cgroupParent = $cgroupParent;

        return $this;
    }

    /**
     * @return int
     */
    public function getBlkioWeight(): ?int
    {
        return $this->blkioWeight;
    }

    /**
     * @param int $blkioWeight
     *
     * @return self
     */
    public function setBlkioWeight(?int $blkioWeight): self
    {
        $this->blkioWeight = $blkioWeight;

        return $this;
    }

    /**
     * @return ResourcesBlkioWeightDeviceItem[]
     */
    public function getBlkioWeightDevice(): ?array
    {
        return $this->blkioWeightDevice;
    }

    /**
     * @param ResourcesBlkioWeightDeviceItem[] $blkioWeightDevice
     *
     * @return self
     */
    public function setBlkioWeightDevice(?array $blkioWeightDevice): self
    {
        $this->blkioWeightDevice = $blkioWeightDevice;

        return $this;
    }

    /**
     * @return ThrottleDevice[]
     */
    public function getBlkioDeviceReadBps(): ?array
    {
        return $this->blkioDeviceReadBps;
    }

    /**
     * @param ThrottleDevice[] $blkioDeviceReadBps
     *
     * @return self
     */
    public function setBlkioDeviceReadBps(?array $blkioDeviceReadBps): self
    {
        $this->blkioDeviceReadBps = $blkioDeviceReadBps;

        return $this;
    }

    /**
     * @return ThrottleDevice[]
     */
    public function getBlkioDeviceWriteBps(): ?array
    {
        return $this->blkioDeviceWriteBps;
    }

    /**
     * @param ThrottleDevice[] $blkioDeviceWriteBps
     *
     * @return self
     */
    public function setBlkioDeviceWriteBps(?array $blkioDeviceWriteBps): self
    {
        $this->blkioDeviceWriteBps = $blkioDeviceWriteBps;

        return $this;
    }

    /**
     * @return ThrottleDevice[]
     */
    public function getBlkioDeviceReadIOps(): ?array
    {
        return $this->blkioDeviceReadIOps;
    }

    /**
     * @param ThrottleDevice[] $blkioDeviceReadIOps
     *
     * @return self
     */
    public function setBlkioDeviceReadIOps(?array $blkioDeviceReadIOps): self
    {
        $this->blkioDeviceReadIOps = $blkioDeviceReadIOps;

        return $this;
    }

    /**
     * @return ThrottleDevice[]
     */
    public function getBlkioDeviceWriteIOps(): ?array
    {
        return $this->blkioDeviceWriteIOps;
    }

    /**
     * @param ThrottleDevice[] $blkioDeviceWriteIOps
     *
     * @return self
     */
    public function setBlkioDeviceWriteIOps(?array $blkioDeviceWriteIOps): self
    {
        $this->blkioDeviceWriteIOps = $blkioDeviceWriteIOps;

        return $this;
    }

    /**
     * @return int
     */
    public function getCpuPeriod(): ?int
    {
        return $this->cpuPeriod;
    }

    /**
     * @param int $cpuPeriod
     *
     * @return self
     */
    public function setCpuPeriod(?int $cpuPeriod): self
    {
        $this->cpuPeriod = $cpuPeriod;

        return $this;
    }

    /**
     * @return int
     */
    public function getCpuQuota(): ?int
    {
        return $this->cpuQuota;
    }

    /**
     * @param int $cpuQuota
     *
     * @return self
     */
    public function setCpuQuota(?int $cpuQuota): self
    {
        $this->cpuQuota = $cpuQuota;

        return $this;
    }

    /**
     * @return int
     */
    public function getCpuRealtimePeriod(): ?int
    {
        return $this->cpuRealtimePeriod;
    }

    /**
     * @param int $cpuRealtimePeriod
     *
     * @return self
     */
    public function setCpuRealtimePeriod(?int $cpuRealtimePeriod): self
    {
        $this->cpuRealtimePeriod = $cpuRealtimePeriod;

        return $this;
    }

    /**
     * @return int
     */
    public function getCpuRealtimeRuntime(): ?int
    {
        return $this->cpuRealtimeRuntime;
    }

    /**
     * @param int $cpuRealtimeRuntime
     *
     * @return self
     */
    public function setCpuRealtimeRuntime(?int $cpuRealtimeRuntime): self
    {
        $this->cpuRealtimeRuntime = $cpuRealtimeRuntime;

        return $this;
    }

    /**
     * @return string
     */
    public function getCpusetCpus(): ?string
    {
        return $this->cpusetCpus;
    }

    /**
     * @param string $cpusetCpus
     *
     * @return self
     */
    public function setCpusetCpus(?string $cpusetCpus): self
    {
        $this->cpusetCpus = $cpusetCpus;

        return $this;
    }

    /**
     * @return string
     */
    public function getCpusetMems(): ?string
    {
        return $this->cpusetMems;
    }

    /**
     * @param string $cpusetMems
     *
     * @return self
     */
    public function setCpusetMems(?string $cpusetMems): self
    {
        $this->cpusetMems = $cpusetMems;

        return $this;
    }

    /**
     * @return DeviceMapping[]
     */
    public function getDevices(): ?array
    {
        return $this->devices;
    }

    /**
     * @param DeviceMapping[] $devices
     *
     * @return self
     */
    public function setDevices(?array $devices): self
    {
        $this->devices = $devices;

        return $this;
    }

    /**
     * @return int
     */
    public function getDiskQuota(): ?int
    {
        return $this->diskQuota;
    }

    /**
     * @param int $diskQuota
     *
     * @return self
     */
    public function setDiskQuota(?int $diskQuota): self
    {
        $this->diskQuota = $diskQuota;

        return $this;
    }

    /**
     * @return int
     */
    public function getKernelMemory(): ?int
    {
        return $this->kernelMemory;
    }

    /**
     * @param int $kernelMemory
     *
     * @return self
     */
    public function setKernelMemory(?int $kernelMemory): self
    {
        $this->kernelMemory = $kernelMemory;

        return $this;
    }

    /**
     * @return int
     */
    public function getMemoryReservation(): ?int
    {
        return $this->memoryReservation;
    }

    /**
     * @param int $memoryReservation
     *
     * @return self
     */
    public function setMemoryReservation(?int $memoryReservation): self
    {
        $this->memoryReservation = $memoryReservation;

        return $this;
    }

    /**
     * @return int
     */
    public function getMemorySwap(): ?int
    {
        return $this->memorySwap;
    }

    /**
     * @param int $memorySwap
     *
     * @return self
     */
    public function setMemorySwap(?int $memorySwap): self
    {
        $this->memorySwap = $memorySwap;

        return $this;
    }

    /**
     * @return int
     */
    public function getMemorySwappiness(): ?int
    {
        return $this->memorySwappiness;
    }

    /**
     * @param int $memorySwappiness
     *
     * @return self
     */
    public function setMemorySwappiness(?int $memorySwappiness): self
    {
        $this->memorySwappiness = $memorySwappiness;

        return $this;
    }

    /**
     * @return int
     */
    public function getNanoCPUs(): ?int
    {
        return $this->nanoCPUs;
    }

    /**
     * @param int $nanoCPUs
     *
     * @return self
     */
    public function setNanoCPUs(?int $nanoCPUs): self
    {
        $this->nanoCPUs = $nanoCPUs;

        return $this;
    }

    /**
     * @return bool
     */
    public function getOomKillDisable(): ?bool
    {
        return $this->oomKillDisable;
    }

    /**
     * @param bool $oomKillDisable
     *
     * @return self
     */
    public function setOomKillDisable(?bool $oomKillDisable): self
    {
        $this->oomKillDisable = $oomKillDisable;

        return $this;
    }

    /**
     * @return int
     */
    public function getPidsLimit(): ?int
    {
        return $this->pidsLimit;
    }

    /**
     * @param int $pidsLimit
     *
     * @return self
     */
    public function setPidsLimit(?int $pidsLimit): self
    {
        $this->pidsLimit = $pidsLimit;

        return $this;
    }

    /**
     * @return ResourcesUlimitsItem[]
     */
    public function getUlimits(): ?array
    {
        return $this->ulimits;
    }

    /**
     * @param ResourcesUlimitsItem[] $ulimits
     *
     * @return self
     */
    public function setUlimits(?array $ulimits): self
    {
        $this->ulimits = $ulimits;

        return $this;
    }

    /**
     * @return int
     */
    public function getCpuCount(): ?int
    {
        return $this->cpuCount;
    }

    /**
     * @param int $cpuCount
     *
     * @return self
     */
    public function setCpuCount(?int $cpuCount): self
    {
        $this->cpuCount = $cpuCount;

        return $this;
    }

    /**
     * @return int
     */
    public function getCpuPercent(): ?int
    {
        return $this->cpuPercent;
    }

    /**
     * @param int $cpuPercent
     *
     * @return self
     */
    public function setCpuPercent(?int $cpuPercent): self
    {
        $this->cpuPercent = $cpuPercent;

        return $this;
    }

    /**
     * @return int
     */
    public function getIOMaximumIOps(): ?int
    {
        return $this->iOMaximumIOps;
    }

    /**
     * @param int $iOMaximumIOps
     *
     * @return self
     */
    public function setIOMaximumIOps(?int $iOMaximumIOps): self
    {
        $this->iOMaximumIOps = $iOMaximumIOps;

        return $this;
    }

    /**
     * @return int
     */
    public function getIOMaximumBandwidth(): ?int
    {
        return $this->iOMaximumBandwidth;
    }

    /**
     * @param int $iOMaximumBandwidth
     *
     * @return self
     */
    public function setIOMaximumBandwidth(?int $iOMaximumBandwidth): self
    {
        $this->iOMaximumBandwidth = $iOMaximumBandwidth;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getBinds(): ?array
    {
        return $this->binds;
    }

    /**
     * @param string[] $binds
     *
     * @return self
     */
    public function setBinds(?array $binds): self
    {
        $this->binds = $binds;

        return $this;
    }

    /**
     * @return string
     */
    public function getContainerIDFile(): ?string
    {
        return $this->containerIDFile;
    }

    /**
     * @param string $containerIDFile
     *
     * @return self
     */
    public function setContainerIDFile(?string $containerIDFile): self
    {
        $this->containerIDFile = $containerIDFile;

        return $this;
    }

    /**
     * @return HostConfigLogConfig
     */
    public function getLogConfig(): ?HostConfigLogConfig
    {
        return $this->logConfig;
    }

    /**
     * @param HostConfigLogConfig $logConfig
     *
     * @return self
     */
    public function setLogConfig(?HostConfigLogConfig $logConfig): self
    {
        $this->logConfig = $logConfig;

        return $this;
    }

    /**
     * @return string
     */
    public function getNetworkMode(): ?string
    {
        return $this->networkMode;
    }

    /**
     * @param string $networkMode
     *
     * @return self
     */
    public function setNetworkMode(?string $networkMode): self
    {
        $this->networkMode = $networkMode;

        return $this;
    }

    /**
     * @return HostConfigPortBindingsItem[]
     */
    public function getPortBindings(): ?\ArrayObject
    {
        return $this->portBindings;
    }

    /**
     * @param HostConfigPortBindingsItem[] $portBindings
     *
     * @return self
     */
    public function setPortBindings(?\ArrayObject $portBindings): self
    {
        $this->portBindings = $portBindings;

        return $this;
    }

    /**
     * @return RestartPolicy
     */
    public function getRestartPolicy(): ?RestartPolicy
    {
        return $this->restartPolicy;
    }

    /**
     * @param RestartPolicy $restartPolicy
     *
     * @return self
     */
    public function setRestartPolicy(?RestartPolicy $restartPolicy): self
    {
        $this->restartPolicy = $restartPolicy;

        return $this;
    }

    /**
     * @return bool
     */
    public function getAutoRemove(): ?bool
    {
        return $this->autoRemove;
    }

    /**
     * @param bool $autoRemove
     *
     * @return self
     */
    public function setAutoRemove(?bool $autoRemove): self
    {
        $this->autoRemove = $autoRemove;

        return $this;
    }

    /**
     * @return string
     */
    public function getVolumeDriver(): ?string
    {
        return $this->volumeDriver;
    }

    /**
     * @param string $volumeDriver
     *
     * @return self
     */
    public function setVolumeDriver(?string $volumeDriver): self
    {
        $this->volumeDriver = $volumeDriver;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getVolumesFrom(): ?array
    {
        return $this->volumesFrom;
    }

    /**
     * @param string[] $volumesFrom
     *
     * @return self
     */
    public function setVolumesFrom(?array $volumesFrom): self
    {
        $this->volumesFrom = $volumesFrom;

        return $this;
    }

    /**
     * @return Mount[]
     */
    public function getMounts(): ?array
    {
        return $this->mounts;
    }

    /**
     * @param Mount[] $mounts
     *
     * @return self
     */
    public function setMounts(?array $mounts): self
    {
        $this->mounts = $mounts;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getCapAdd(): ?array
    {
        return $this->capAdd;
    }

    /**
     * @param string[] $capAdd
     *
     * @return self
     */
    public function setCapAdd(?array $capAdd): self
    {
        $this->capAdd = $capAdd;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getCapDrop(): ?array
    {
        return $this->capDrop;
    }

    /**
     * @param string[] $capDrop
     *
     * @return self
     */
    public function setCapDrop(?array $capDrop): self
    {
        $this->capDrop = $capDrop;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getDns(): ?array
    {
        return $this->dns;
    }

    /**
     * @param string[] $dns
     *
     * @return self
     */
    public function setDns(?array $dns): self
    {
        $this->dns = $dns;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getDnsOptions(): ?array
    {
        return $this->dnsOptions;
    }

    /**
     * @param string[] $dnsOptions
     *
     * @return self
     */
    public function setDnsOptions(?array $dnsOptions): self
    {
        $this->dnsOptions = $dnsOptions;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getDnsSearch(): ?array
    {
        return $this->dnsSearch;
    }

    /**
     * @param string[] $dnsSearch
     *
     * @return self
     */
    public function setDnsSearch(?array $dnsSearch): self
    {
        $this->dnsSearch = $dnsSearch;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getExtraHosts(): ?array
    {
        return $this->extraHosts;
    }

    /**
     * @param string[] $extraHosts
     *
     * @return self
     */
    public function setExtraHosts(?array $extraHosts): self
    {
        $this->extraHosts = $extraHosts;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getGroupAdd(): ?array
    {
        return $this->groupAdd;
    }

    /**
     * @param string[] $groupAdd
     *
     * @return self
     */
    public function setGroupAdd(?array $groupAdd): self
    {
        $this->groupAdd = $groupAdd;

        return $this;
    }

    /**
     * @return string
     */
    public function getIpcMode(): ?string
    {
        return $this->ipcMode;
    }

    /**
     * @param string $ipcMode
     *
     * @return self
     */
    public function setIpcMode(?string $ipcMode): self
    {
        $this->ipcMode = $ipcMode;

        return $this;
    }

    /**
     * @return string
     */
    public function getCgroup(): ?string
    {
        return $this->cgroup;
    }

    /**
     * @param string $cgroup
     *
     * @return self
     */
    public function setCgroup(?string $cgroup): self
    {
        $this->cgroup = $cgroup;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getLinks(): ?array
    {
        return $this->links;
    }

    /**
     * @param string[] $links
     *
     * @return self
     */
    public function setLinks(?array $links): self
    {
        $this->links = $links;

        return $this;
    }

    /**
     * @return int
     */
    public function getOomScoreAdj(): ?int
    {
        return $this->oomScoreAdj;
    }

    /**
     * @param int $oomScoreAdj
     *
     * @return self
     */
    public function setOomScoreAdj(?int $oomScoreAdj): self
    {
        $this->oomScoreAdj = $oomScoreAdj;

        return $this;
    }

    /**
     * @return string
     */
    public function getPidMode(): ?string
    {
        return $this->pidMode;
    }

    /**
     * @param string $pidMode
     *
     * @return self
     */
    public function setPidMode(?string $pidMode): self
    {
        $this->pidMode = $pidMode;

        return $this;
    }

    /**
     * @return bool
     */
    public function getPrivileged(): ?bool
    {
        return $this->privileged;
    }

    /**
     * @param bool $privileged
     *
     * @return self
     */
    public function setPrivileged(?bool $privileged): self
    {
        $this->privileged = $privileged;

        return $this;
    }

    /**
     * @return bool
     */
    public function getPublishAllPorts(): ?bool
    {
        return $this->publishAllPorts;
    }

    /**
     * @param bool $publishAllPorts
     *
     * @return self
     */
    public function setPublishAllPorts(?bool $publishAllPorts): self
    {
        $this->publishAllPorts = $publishAllPorts;

        return $this;
    }

    /**
     * @return bool
     */
    public function getReadonlyRootfs(): ?bool
    {
        return $this->readonlyRootfs;
    }

    /**
     * @param bool $readonlyRootfs
     *
     * @return self
     */
    public function setReadonlyRootfs(?bool $readonlyRootfs): self
    {
        $this->readonlyRootfs = $readonlyRootfs;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getSecurityOpt(): ?array
    {
        return $this->securityOpt;
    }

    /**
     * @param string[] $securityOpt
     *
     * @return self
     */
    public function setSecurityOpt(?array $securityOpt): self
    {
        $this->securityOpt = $securityOpt;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getStorageOpt(): ?\ArrayObject
    {
        return $this->storageOpt;
    }

    /**
     * @param string[] $storageOpt
     *
     * @return self
     */
    public function setStorageOpt(?\ArrayObject $storageOpt): self
    {
        $this->storageOpt = $storageOpt;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getTmpfs(): ?\ArrayObject
    {
        return $this->tmpfs;
    }

    /**
     * @param string[] $tmpfs
     *
     * @return self
     */
    public function setTmpfs(?\ArrayObject $tmpfs): self
    {
        $this->tmpfs = $tmpfs;

        return $this;
    }

    /**
     * @return string
     */
    public function getUTSMode(): ?string
    {
        return $this->uTSMode;
    }

    /**
     * @param string $uTSMode
     *
     * @return self
     */
    public function setUTSMode(?string $uTSMode): self
    {
        $this->uTSMode = $uTSMode;

        return $this;
    }

    /**
     * @return string
     */
    public function getUsernsMode(): ?string
    {
        return $this->usernsMode;
    }

    /**
     * @param string $usernsMode
     *
     * @return self
     */
    public function setUsernsMode(?string $usernsMode): self
    {
        $this->usernsMode = $usernsMode;

        return $this;
    }

    /**
     * @return int
     */
    public function getShmSize(): ?int
    {
        return $this->shmSize;
    }

    /**
     * @param int $shmSize
     *
     * @return self
     */
    public function setShmSize(?int $shmSize): self
    {
        $this->shmSize = $shmSize;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getSysctls(): ?\ArrayObject
    {
        return $this->sysctls;
    }

    /**
     * @param string[] $sysctls
     *
     * @return self
     */
    public function setSysctls(?\ArrayObject $sysctls): self
    {
        $this->sysctls = $sysctls;

        return $this;
    }

    /**
     * @return string
     */
    public function getRuntime(): ?string
    {
        return $this->runtime;
    }

    /**
     * @param string $runtime
     *
     * @return self
     */
    public function setRuntime(?string $runtime): self
    {
        $this->runtime = $runtime;

        return $this;
    }

    /**
     * @return int[]
     */
    public function getConsoleSize(): ?array
    {
        return $this->consoleSize;
    }

    /**
     * @param int[] $consoleSize
     *
     * @return self
     */
    public function setConsoleSize(?array $consoleSize): self
    {
        $this->consoleSize = $consoleSize;

        return $this;
    }

    /**
     * @return string
     */
    public function getIsolation(): ?string
    {
        return $this->isolation;
    }

    /**
     * @param string $isolation
     *
     * @return self
     */
    public function setIsolation(?string $isolation): self
    {
        $this->isolation = $isolation;

        return $this;
    }
}
