<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class ImagesPrunePostResponse200
{
    /**
     * @var ImageDeleteResponse[]
     */
    protected $imagesDeleted;
    /**
     * @var int
     */
    protected $spaceReclaimed;

    /**
     * @return ImageDeleteResponse[]
     */
    public function getImagesDeleted(): ?array
    {
        return $this->imagesDeleted;
    }

    /**
     * @param ImageDeleteResponse[] $imagesDeleted
     *
     * @return self
     */
    public function setImagesDeleted(?array $imagesDeleted): self
    {
        $this->imagesDeleted = $imagesDeleted;

        return $this;
    }

    /**
     * @return int
     */
    public function getSpaceReclaimed(): ?int
    {
        return $this->spaceReclaimed;
    }

    /**
     * @param int $spaceReclaimed
     *
     * @return self
     */
    public function setSpaceReclaimed(?int $spaceReclaimed): self
    {
        $this->spaceReclaimed = $spaceReclaimed;

        return $this;
    }
}
