<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class InfoGetResponse200Plugins
{
    /**
     * @var string[]
     */
    protected $volume;
    /**
     * @var string[]
     */
    protected $network;

    /**
     * @return string[]
     */
    public function getVolume(): ?array
    {
        return $this->volume;
    }

    /**
     * @param string[] $volume
     *
     * @return self
     */
    public function setVolume(?array $volume): self
    {
        $this->volume = $volume;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getNetwork(): ?array
    {
        return $this->network;
    }

    /**
     * @param string[] $network
     *
     * @return self
     */
    public function setNetwork(?array $network): self
    {
        $this->network = $network;

        return $this;
    }
}
