<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class InfoGetResponse200
{
    /**
     * @var string
     */
    protected $architecture;
    /**
     * @var int
     */
    protected $containers;
    /**
     * @var int
     */
    protected $containersRunning;
    /**
     * @var int
     */
    protected $containersStopped;
    /**
     * @var int
     */
    protected $containersPaused;
    /**
     * @var bool
     */
    protected $cpuCfsPeriod;
    /**
     * @var bool
     */
    protected $cpuCfsQuota;
    /**
     * @var bool
     */
    protected $debug;
    /**
     * @var string
     */
    protected $discoveryBackend;
    /**
     * @var string
     */
    protected $dockerRootDir;
    /**
     * @var string
     */
    protected $driver;
    /**
     * @var string[][]
     */
    protected $driverStatus;
    /**
     * @var string[][]
     */
    protected $systemStatus;
    /**
     * @var InfoGetResponse200Plugins
     */
    protected $plugins;
    /**
     * @var bool
     */
    protected $experimentalBuild;
    /**
     * @var string
     */
    protected $httpProxy;
    /**
     * @var string
     */
    protected $httpsProxy;
    /**
     * @var string
     */
    protected $iD;
    /**
     * @var bool
     */
    protected $iPv4Forwarding;
    /**
     * @var int
     */
    protected $images;
    /**
     * @var string
     */
    protected $indexServerAddress;
    /**
     * @var string
     */
    protected $initPath;
    /**
     * @var string
     */
    protected $initSha1;
    /**
     * @var string
     */
    protected $kernelVersion;
    /**
     * @var string[]
     */
    protected $labels;
    /**
     * @var int
     */
    protected $memTotal;
    /**
     * @var bool
     */
    protected $memoryLimit;
    /**
     * @var int
     */
    protected $nCPU;
    /**
     * @var int
     */
    protected $nEventsListener;
    /**
     * @var int
     */
    protected $nFd;
    /**
     * @var int
     */
    protected $nGoroutines;
    /**
     * @var string
     */
    protected $name;
    /**
     * @var string
     */
    protected $noProxy;
    /**
     * @var bool
     */
    protected $oomKillDisable;
    /**
     * @var string
     */
    protected $oSType;
    /**
     * @var int
     */
    protected $oomScoreAdj;
    /**
     * @var string
     */
    protected $operatingSystem;
    /**
     * @var InfoGetResponse200RegistryConfig
     */
    protected $registryConfig;
    /**
     * @var bool
     */
    protected $swapLimit;
    /**
     * @var string
     */
    protected $systemTime;
    /**
     * @var string
     */
    protected $serverVersion;

    /**
     * @return string
     */
    public function getArchitecture(): ?string
    {
        return $this->architecture;
    }

    /**
     * @param string $architecture
     *
     * @return self
     */
    public function setArchitecture(?string $architecture): self
    {
        $this->architecture = $architecture;

        return $this;
    }

    /**
     * @return int
     */
    public function getContainers(): ?int
    {
        return $this->containers;
    }

    /**
     * @param int $containers
     *
     * @return self
     */
    public function setContainers(?int $containers): self
    {
        $this->containers = $containers;

        return $this;
    }

    /**
     * @return int
     */
    public function getContainersRunning(): ?int
    {
        return $this->containersRunning;
    }

    /**
     * @param int $containersRunning
     *
     * @return self
     */
    public function setContainersRunning(?int $containersRunning): self
    {
        $this->containersRunning = $containersRunning;

        return $this;
    }

    /**
     * @return int
     */
    public function getContainersStopped(): ?int
    {
        return $this->containersStopped;
    }

    /**
     * @param int $containersStopped
     *
     * @return self
     */
    public function setContainersStopped(?int $containersStopped): self
    {
        $this->containersStopped = $containersStopped;

        return $this;
    }

    /**
     * @return int
     */
    public function getContainersPaused(): ?int
    {
        return $this->containersPaused;
    }

    /**
     * @param int $containersPaused
     *
     * @return self
     */
    public function setContainersPaused(?int $containersPaused): self
    {
        $this->containersPaused = $containersPaused;

        return $this;
    }

    /**
     * @return bool
     */
    public function getCpuCfsPeriod(): ?bool
    {
        return $this->cpuCfsPeriod;
    }

    /**
     * @param bool $cpuCfsPeriod
     *
     * @return self
     */
    public function setCpuCfsPeriod(?bool $cpuCfsPeriod): self
    {
        $this->cpuCfsPeriod = $cpuCfsPeriod;

        return $this;
    }

    /**
     * @return bool
     */
    public function getCpuCfsQuota(): ?bool
    {
        return $this->cpuCfsQuota;
    }

    /**
     * @param bool $cpuCfsQuota
     *
     * @return self
     */
    public function setCpuCfsQuota(?bool $cpuCfsQuota): self
    {
        $this->cpuCfsQuota = $cpuCfsQuota;

        return $this;
    }

    /**
     * @return bool
     */
    public function getDebug(): ?bool
    {
        return $this->debug;
    }

    /**
     * @param bool $debug
     *
     * @return self
     */
    public function setDebug(?bool $debug): self
    {
        $this->debug = $debug;

        return $this;
    }

    /**
     * @return string
     */
    public function getDiscoveryBackend(): ?string
    {
        return $this->discoveryBackend;
    }

    /**
     * @param string $discoveryBackend
     *
     * @return self
     */
    public function setDiscoveryBackend(?string $discoveryBackend): self
    {
        $this->discoveryBackend = $discoveryBackend;

        return $this;
    }

    /**
     * @return string
     */
    public function getDockerRootDir(): ?string
    {
        return $this->dockerRootDir;
    }

    /**
     * @param string $dockerRootDir
     *
     * @return self
     */
    public function setDockerRootDir(?string $dockerRootDir): self
    {
        $this->dockerRootDir = $dockerRootDir;

        return $this;
    }

    /**
     * @return string
     */
    public function getDriver(): ?string
    {
        return $this->driver;
    }

    /**
     * @param string $driver
     *
     * @return self
     */
    public function setDriver(?string $driver): self
    {
        $this->driver = $driver;

        return $this;
    }

    /**
     * @return string[][]
     */
    public function getDriverStatus(): ?array
    {
        return $this->driverStatus;
    }

    /**
     * @param string[][] $driverStatus
     *
     * @return self
     */
    public function setDriverStatus(?array $driverStatus): self
    {
        $this->driverStatus = $driverStatus;

        return $this;
    }

    /**
     * @return string[][]
     */
    public function getSystemStatus(): ?array
    {
        return $this->systemStatus;
    }

    /**
     * @param string[][] $systemStatus
     *
     * @return self
     */
    public function setSystemStatus(?array $systemStatus): self
    {
        $this->systemStatus = $systemStatus;

        return $this;
    }

    /**
     * @return InfoGetResponse200Plugins
     */
    public function getPlugins(): ?InfoGetResponse200Plugins
    {
        return $this->plugins;
    }

    /**
     * @param InfoGetResponse200Plugins $plugins
     *
     * @return self
     */
    public function setPlugins(?InfoGetResponse200Plugins $plugins): self
    {
        $this->plugins = $plugins;

        return $this;
    }

    /**
     * @return bool
     */
    public function getExperimentalBuild(): ?bool
    {
        return $this->experimentalBuild;
    }

    /**
     * @param bool $experimentalBuild
     *
     * @return self
     */
    public function setExperimentalBuild(?bool $experimentalBuild): self
    {
        $this->experimentalBuild = $experimentalBuild;

        return $this;
    }

    /**
     * @return string
     */
    public function getHttpProxy(): ?string
    {
        return $this->httpProxy;
    }

    /**
     * @param string $httpProxy
     *
     * @return self
     */
    public function setHttpProxy(?string $httpProxy): self
    {
        $this->httpProxy = $httpProxy;

        return $this;
    }

    /**
     * @return string
     */
    public function getHttpsProxy(): ?string
    {
        return $this->httpsProxy;
    }

    /**
     * @param string $httpsProxy
     *
     * @return self
     */
    public function setHttpsProxy(?string $httpsProxy): self
    {
        $this->httpsProxy = $httpsProxy;

        return $this;
    }

    /**
     * @return string
     */
    public function getID(): ?string
    {
        return $this->iD;
    }

    /**
     * @param string $iD
     *
     * @return self
     */
    public function setID(?string $iD): self
    {
        $this->iD = $iD;

        return $this;
    }

    /**
     * @return bool
     */
    public function getIPv4Forwarding(): ?bool
    {
        return $this->iPv4Forwarding;
    }

    /**
     * @param bool $iPv4Forwarding
     *
     * @return self
     */
    public function setIPv4Forwarding(?bool $iPv4Forwarding): self
    {
        $this->iPv4Forwarding = $iPv4Forwarding;

        return $this;
    }

    /**
     * @return int
     */
    public function getImages(): ?int
    {
        return $this->images;
    }

    /**
     * @param int $images
     *
     * @return self
     */
    public function setImages(?int $images): self
    {
        $this->images = $images;

        return $this;
    }

    /**
     * @return string
     */
    public function getIndexServerAddress(): ?string
    {
        return $this->indexServerAddress;
    }

    /**
     * @param string $indexServerAddress
     *
     * @return self
     */
    public function setIndexServerAddress(?string $indexServerAddress): self
    {
        $this->indexServerAddress = $indexServerAddress;

        return $this;
    }

    /**
     * @return string
     */
    public function getInitPath(): ?string
    {
        return $this->initPath;
    }

    /**
     * @param string $initPath
     *
     * @return self
     */
    public function setInitPath(?string $initPath): self
    {
        $this->initPath = $initPath;

        return $this;
    }

    /**
     * @return string
     */
    public function getInitSha1(): ?string
    {
        return $this->initSha1;
    }

    /**
     * @param string $initSha1
     *
     * @return self
     */
    public function setInitSha1(?string $initSha1): self
    {
        $this->initSha1 = $initSha1;

        return $this;
    }

    /**
     * @return string
     */
    public function getKernelVersion(): ?string
    {
        return $this->kernelVersion;
    }

    /**
     * @param string $kernelVersion
     *
     * @return self
     */
    public function setKernelVersion(?string $kernelVersion): self
    {
        $this->kernelVersion = $kernelVersion;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getLabels(): ?array
    {
        return $this->labels;
    }

    /**
     * @param string[] $labels
     *
     * @return self
     */
    public function setLabels(?array $labels): self
    {
        $this->labels = $labels;

        return $this;
    }

    /**
     * @return int
     */
    public function getMemTotal(): ?int
    {
        return $this->memTotal;
    }

    /**
     * @param int $memTotal
     *
     * @return self
     */
    public function setMemTotal(?int $memTotal): self
    {
        $this->memTotal = $memTotal;

        return $this;
    }

    /**
     * @return bool
     */
    public function getMemoryLimit(): ?bool
    {
        return $this->memoryLimit;
    }

    /**
     * @param bool $memoryLimit
     *
     * @return self
     */
    public function setMemoryLimit(?bool $memoryLimit): self
    {
        $this->memoryLimit = $memoryLimit;

        return $this;
    }

    /**
     * @return int
     */
    public function getNCPU(): ?int
    {
        return $this->nCPU;
    }

    /**
     * @param int $nCPU
     *
     * @return self
     */
    public function setNCPU(?int $nCPU): self
    {
        $this->nCPU = $nCPU;

        return $this;
    }

    /**
     * @return int
     */
    public function getNEventsListener(): ?int
    {
        return $this->nEventsListener;
    }

    /**
     * @param int $nEventsListener
     *
     * @return self
     */
    public function setNEventsListener(?int $nEventsListener): self
    {
        $this->nEventsListener = $nEventsListener;

        return $this;
    }

    /**
     * @return int
     */
    public function getNFd(): ?int
    {
        return $this->nFd;
    }

    /**
     * @param int $nFd
     *
     * @return self
     */
    public function setNFd(?int $nFd): self
    {
        $this->nFd = $nFd;

        return $this;
    }

    /**
     * @return int
     */
    public function getNGoroutines(): ?int
    {
        return $this->nGoroutines;
    }

    /**
     * @param int $nGoroutines
     *
     * @return self
     */
    public function setNGoroutines(?int $nGoroutines): self
    {
        $this->nGoroutines = $nGoroutines;

        return $this;
    }

    /**
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string
     */
    public function getNoProxy(): ?string
    {
        return $this->noProxy;
    }

    /**
     * @param string $noProxy
     *
     * @return self
     */
    public function setNoProxy(?string $noProxy): self
    {
        $this->noProxy = $noProxy;

        return $this;
    }

    /**
     * @return bool
     */
    public function getOomKillDisable(): ?bool
    {
        return $this->oomKillDisable;
    }

    /**
     * @param bool $oomKillDisable
     *
     * @return self
     */
    public function setOomKillDisable(?bool $oomKillDisable): self
    {
        $this->oomKillDisable = $oomKillDisable;

        return $this;
    }

    /**
     * @return string
     */
    public function getOSType(): ?string
    {
        return $this->oSType;
    }

    /**
     * @param string $oSType
     *
     * @return self
     */
    public function setOSType(?string $oSType): self
    {
        $this->oSType = $oSType;

        return $this;
    }

    /**
     * @return int
     */
    public function getOomScoreAdj(): ?int
    {
        return $this->oomScoreAdj;
    }

    /**
     * @param int $oomScoreAdj
     *
     * @return self
     */
    public function setOomScoreAdj(?int $oomScoreAdj): self
    {
        $this->oomScoreAdj = $oomScoreAdj;

        return $this;
    }

    /**
     * @return string
     */
    public function getOperatingSystem(): ?string
    {
        return $this->operatingSystem;
    }

    /**
     * @param string $operatingSystem
     *
     * @return self
     */
    public function setOperatingSystem(?string $operatingSystem): self
    {
        $this->operatingSystem = $operatingSystem;

        return $this;
    }

    /**
     * @return InfoGetResponse200RegistryConfig
     */
    public function getRegistryConfig(): ?InfoGetResponse200RegistryConfig
    {
        return $this->registryConfig;
    }

    /**
     * @param InfoGetResponse200RegistryConfig $registryConfig
     *
     * @return self
     */
    public function setRegistryConfig(?InfoGetResponse200RegistryConfig $registryConfig): self
    {
        $this->registryConfig = $registryConfig;

        return $this;
    }

    /**
     * @return bool
     */
    public function getSwapLimit(): ?bool
    {
        return $this->swapLimit;
    }

    /**
     * @param bool $swapLimit
     *
     * @return self
     */
    public function setSwapLimit(?bool $swapLimit): self
    {
        $this->swapLimit = $swapLimit;

        return $this;
    }

    /**
     * @return string
     */
    public function getSystemTime(): ?string
    {
        return $this->systemTime;
    }

    /**
     * @param string $systemTime
     *
     * @return self
     */
    public function setSystemTime(?string $systemTime): self
    {
        $this->systemTime = $systemTime;

        return $this;
    }

    /**
     * @return string
     */
    public function getServerVersion(): ?string
    {
        return $this->serverVersion;
    }

    /**
     * @param string $serverVersion
     *
     * @return self
     */
    public function setServerVersion(?string $serverVersion): self
    {
        $this->serverVersion = $serverVersion;

        return $this;
    }
}
