<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class NetworksPrunePostResponse200
{
    /**
     * @var string[]
     */
    protected $volumesDeleted;

    /**
     * @return string[]
     */
    public function getVolumesDeleted(): ?array
    {
        return $this->volumesDeleted;
    }

    /**
     * @param string[] $volumesDeleted
     *
     * @return self
     */
    public function setVolumesDeleted(?array $volumesDeleted): self
    {
        $this->volumesDeleted = $volumesDeleted;

        return $this;
    }
}
