<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class NetworksIdDisconnectPostBody
{
    /**
     * @var string
     */
    protected $container;
    /**
     * @var bool
     */
    protected $force;

    /**
     * @return string
     */
    public function getContainer(): ?string
    {
        return $this->container;
    }

    /**
     * @param string $container
     *
     * @return self
     */
    public function setContainer(?string $container): self
    {
        $this->container = $container;

        return $this;
    }

    /**
     * @return bool
     */
    public function getForce(): ?bool
    {
        return $this->force;
    }

    /**
     * @param bool $force
     *
     * @return self
     */
    public function setForce(?bool $force): self
    {
        $this->force = $force;

        return $this;
    }
}
