<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class SwarmSpecCAConfig
{
    /**
     * The duration node certificates are issued for.
     *
     * @var int
     */
    protected $nodeCertExpiry;
    /**
     * Configuration for forwarding signing requests to an external certificate authority.
     *
     * @var SwarmSpecCAConfigExternalCAsItem[]
     */
    protected $externalCAs;

    /**
     * The duration node certificates are issued for.
     *
     * @return int
     */
    public function getNodeCertExpiry(): ?int
    {
        return $this->nodeCertExpiry;
    }

    /**
     * The duration node certificates are issued for.
     *
     * @param int $nodeCertExpiry
     *
     * @return self
     */
    public function setNodeCertExpiry(?int $nodeCertExpiry): self
    {
        $this->nodeCertExpiry = $nodeCertExpiry;

        return $this;
    }

    /**
     * Configuration for forwarding signing requests to an external certificate authority.
     *
     * @return SwarmSpecCAConfigExternalCAsItem[]
     */
    public function getExternalCAs(): ?array
    {
        return $this->externalCAs;
    }

    /**
     * Configuration for forwarding signing requests to an external certificate authority.
     *
     * @param SwarmSpecCAConfigExternalCAsItem[] $externalCAs
     *
     * @return self
     */
    public function setExternalCAs(?array $externalCAs): self
    {
        $this->externalCAs = $externalCAs;

        return $this;
    }
}
