<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class SwarmUnlockPostBody
{
    /**
     * @var string
     */
    protected $unlockKey;

    /**
     * @return string
     */
    public function getUnlockKey(): ?string
    {
        return $this->unlockKey;
    }

    /**
     * @param string $unlockKey
     *
     * @return self
     */
    public function setUnlockKey(?string $unlockKey): self
    {
        $this->unlockKey = $unlockKey;

        return $this;
    }
}
