<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class SwarmInitPostBody
{
    /**
     * @var string
     */
    protected $listenAddr;
    /**
     * @var string
     */
    protected $advertiseAddr;
    /**
     * @var bool
     */
    protected $forceNewCluster;
    /**
     * @var SwarmSpec
     */
    protected $spec;

    /**
     * @return string
     */
    public function getListenAddr(): ?string
    {
        return $this->listenAddr;
    }

    /**
     * @param string $listenAddr
     *
     * @return self
     */
    public function setListenAddr(?string $listenAddr): self
    {
        $this->listenAddr = $listenAddr;

        return $this;
    }

    /**
     * @return string
     */
    public function getAdvertiseAddr(): ?string
    {
        return $this->advertiseAddr;
    }

    /**
     * @param string $advertiseAddr
     *
     * @return self
     */
    public function setAdvertiseAddr(?string $advertiseAddr): self
    {
        $this->advertiseAddr = $advertiseAddr;

        return $this;
    }

    /**
     * @return bool
     */
    public function getForceNewCluster(): ?bool
    {
        return $this->forceNewCluster;
    }

    /**
     * @param bool $forceNewCluster
     *
     * @return self
     */
    public function setForceNewCluster(?bool $forceNewCluster): self
    {
        $this->forceNewCluster = $forceNewCluster;

        return $this;
    }

    /**
     * @return SwarmSpec
     */
    public function getSpec(): ?SwarmSpec
    {
        return $this->spec;
    }

    /**
     * @param SwarmSpec $spec
     *
     * @return self
     */
    public function setSpec(?SwarmSpec $spec): self
    {
        $this->spec = $spec;

        return $this;
    }
}
