<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class SwarmSpecTaskDefaults
{
    /**
     * @var SwarmSpecTaskDefaultsLogDriver
     */
    protected $logDriver;

    /**
     * @return SwarmSpecTaskDefaultsLogDriver
     */
    public function getLogDriver(): ?SwarmSpecTaskDefaultsLogDriver
    {
        return $this->logDriver;
    }

    /**
     * @param SwarmSpecTaskDefaultsLogDriver $logDriver
     *
     * @return self
     */
    public function setLogDriver(?SwarmSpecTaskDefaultsLogDriver $logDriver): self
    {
        $this->logDriver = $logDriver;

        return $this;
    }
}
