<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class TaskSpecPlacement
{
    /**
     * An array of constraints.
     *
     * @var string[]
     */
    protected $constraints;
    /**
     * Preferences provide a way to make the scheduler aware of factors such as topology. They are provided in order from highest to lowest precedence.
     *
     * @var TaskSpecPlacementPreferencesItem[]
     */
    protected $preferences;
    /**
     * An array of supported platforms.
     *
     * @var TaskSpecPlacementPlatformsItem[]
     */
    protected $platforms;

    /**
     * An array of constraints.
     *
     * @return string[]
     */
    public function getConstraints(): ?array
    {
        return $this->constraints;
    }

    /**
     * An array of constraints.
     *
     * @param string[] $constraints
     *
     * @return self
     */
    public function setConstraints(?array $constraints): self
    {
        $this->constraints = $constraints;

        return $this;
    }

    /**
     * Preferences provide a way to make the scheduler aware of factors such as topology. They are provided in order from highest to lowest precedence.
     *
     * @return TaskSpecPlacementPreferencesItem[]
     */
    public function getPreferences(): ?array
    {
        return $this->preferences;
    }

    /**
     * Preferences provide a way to make the scheduler aware of factors such as topology. They are provided in order from highest to lowest precedence.
     *
     * @param TaskSpecPlacementPreferencesItem[] $preferences
     *
     * @return self
     */
    public function setPreferences(?array $preferences): self
    {
        $this->preferences = $preferences;

        return $this;
    }

    /**
     * An array of supported platforms.
     *
     * @return TaskSpecPlacementPlatformsItem[]
     */
    public function getPlatforms(): ?array
    {
        return $this->platforms;
    }

    /**
     * An array of supported platforms.
     *
     * @param TaskSpecPlacementPlatformsItem[] $platforms
     *
     * @return self
     */
    public function setPlatforms(?array $platforms): self
    {
        $this->platforms = $platforms;

        return $this;
    }
}
