<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class TaskSpecNetworksItem
{
    /**
     * @var string
     */
    protected $target;
    /**
     * @var string[]
     */
    protected $aliases;

    /**
     * @return string
     */
    public function getTarget(): ?string
    {
        return $this->target;
    }

    /**
     * @param string $target
     *
     * @return self
     */
    public function setTarget(?string $target): self
    {
        $this->target = $target;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getAliases(): ?array
    {
        return $this->aliases;
    }

    /**
     * @param string[] $aliases
     *
     * @return self
     */
    public function setAliases(?array $aliases): self
    {
        $this->aliases = $aliases;

        return $this;
    }
}
