<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class VolumesGetResponse200
{
    /**
     * @var Volume[]
     */
    protected $volumes;
    /**
     * @var string[]
     */
    protected $warnings;

    /**
     * @return Volume[]
     */
    public function getVolumes(): ?array
    {
        return $this->volumes;
    }

    /**
     * @param Volume[] $volumes
     *
     * @return self
     */
    public function setVolumes(?array $volumes): self
    {
        $this->volumes = $volumes;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getWarnings(): ?array
    {
        return $this->warnings;
    }

    /**
     * @param string[] $warnings
     *
     * @return self
     */
    public function setWarnings(?array $warnings): self
    {
        $this->warnings = $warnings;

        return $this;
    }
}
